config/routes.rb
Rails.application.routes.draw do


  get 'comics/new'
  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :comics, only: [:new, :create, :index, :show, :edit, :update]
  resources :publishers, only: [:index, :show]
  resources :cartoonists, only: [:index, :show]
  get '/terms', to: 'pages#terms'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartoonist.rb
class Cartoonist < ApplicationRecord
  has_many :comics
  has_many :users
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :user
  belongs_to :publisher
  belongs_to :cartoonist
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :comics
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :comics
  has_many :cartoonists
  has_many :publishers

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about] # top, about の2つのアクションのみ、ログイン無しでもアクセス可能にする
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/cartoonists_controller.rb
class CartoonistsController < ApplicationController
  def index
    @cartoonists = Cartoonist.all
    @user = current_user
  end

  def show
    @cartoonist = Cartoonist.find(params[:id])
    @user = current_user
    @cartoonists = @user.cartoonists
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :require_permission, only:[:edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update]

  def new
    @comic = Comic.new
    @publishers = Publisher.all
    @cartoonists = Cartoonist.all
  end

  def index
    @comics = Comic.all
    @user = current_user
  end

  def show
    @comic = Comic.find(params[:id])
    @user = @comic.user
    @cartoonist = @comic.cartoonist
    @publisher = @comic.publisher
  end

  def edit
    @comic = Comic.find(params[:id])
    @comic.save
    if @comic.user != current_user
      redirect_to comics_path
    end
  end


  # def create
  #   @comic = current_user.comics.build(comic_params)
  #   if @comic.save
  #     flash[:notice] = 'Comic was successfully created.'
  #     redirect_to comic_path(@comic.id)
  #   else
  #     @user = current_user
  #     @comics = Comic.all
  #     @publishers = Publisher.all
  #     @cartoonists = Cartoonist.all
  #     render :new
  #   end
  # end

  def create
    @comic = current_user.comics.build(comic_params)
    @comic.cartoonist = Cartoonist.find(params[:comic][:cartoonist_id].first)
    @comic.publisher = Publisher.find(params[:comic][:publisher_id].first)

    if @comic.save
      flash[:notice] = 'Comic was successfully created.'
      redirect_to comic_path(@comic.id)
    else
      @user = current_user
      @comics = Comic.all
      @publishers = Publisher.all
      @cartoonists = Cartoonist.all
      render :new
    end
  end




  def update
    @comic = Comic.find(params[:id])
    if @comic.update(comic_params)
      flash[:notice] = 'Comic was successfully updated.'
      redirect_to comic_path(@comic.id)
    else
      render :edit
    end
  end

  def destroy
    @comic = Comic.find(params[:id])
    if @comic.destroy
      flash[:notice] = 'Comic was successfully destroyed.'
      redirect_to comics_path
    end
  end

  private

  def comic_params
    params.require(:comic).permit(:title, :body, :cartoonist_id, :publisher_id)
  end


  def require_permission
    @comic = Comic.find(params[:id])
    if @comic.user != current_user
      redirect_to comics_path, alert: "他人の投稿は編集・削除できません。"
    end
  end

  def authorize_user
    @comic = Comic.find(params[:id])
    unless current_user == @comic.user
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to root_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @publishers = Publisher.all
    @user = current_user
  end

  def show
    @publisher = Publisher.find(params[:id])
    @user = current_user
    @publishers = @user.publishers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @comics = @user.comics
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user)
    else
      flash[:error] = 'Failed to update user.'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoonists_helper.rb
module CartoonistsHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cartoonists/index.html.erb
<main>
  <p id = "notice"><%= flash[:notice] %></p>

  <div class = "container px-5 px-sm-0">
    <div class = "row">
      <div class = "col-md-3">
        <%= render 'layouts/sidebar' %>
      </div>


      <div class = "col-md-8 offset-md-1">
        <h2><i class="fas fa-pen-fancy"></i>Cartoonists</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th>作者</th>
              <th colspan = "3"></th>
              <Body></Body>
            </tr>
          </thead>
          <tbody>
            <% @cartoonists.each do |cartoonist| %>
            <tr>
              <td><%= link_to cartoonist.artist_name, cartoonist_path(cartoonist.id)  %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/cartoonists/show.html.erb
<main>
  <p id = "notice"><%= flash[:notice] %></p>

  <div class = "container px-5 px-sm-0" >
    <div class = "row">
      <div class = "col-md-3">
        <%= render 'layouts/sidebar' %>
      </div>


      <div class = "col-md-8 offset-md-1">
        <h2><i class="fas fa-pen-fancy"></i>Cartoonist detail</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th>作品名</th>
              <th>レビュー</th>
              <th>出版社</th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
          <% @cartoonist.comics.each do |comic| %>
            <tr>
              <td><%= link_to comic.title, comic_path(comic.id) %></td>
              <td><%= comic.body %></td>
              <td><%= comic.publisher&.company_name %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/comics/edit.html.erb
<main>
  <p id="notice"><%= notice %></p>
  <%= form_with model:@comic, local:true do |f| %>
    <div class = "contailner">
      <div class = "row">
        <div class = "col-sm-12 col-md-8 col-lg-5 p-5 px-sm-0 mx-auto">
          <h2><i class="fas fa-book-open"></i>Editing Comic</h2>
            <% if @comic.errors.any? %>
            <div id = "error_explanation">
              <h2><%= @comic.errors.count %> errors prohibited this user from being saved:</h2>
                <ul>
                  <% @comic.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>

            <% end %>

            <%= form_with model:@comic, local:true do |f| %>
              <div class = "form-group">
                <%= f.label :title, "作品名" %>
                <%= f.text_field :title %>
              </div>
              <div class = "form-group">
                <%= f.label :body, "レビュー" %>
                <%= f.text_area :body %>
              </div>
              <div class="form-group">
                <%= f.label :artist_name_id, "作者" %>
                <%= select_tag "comic[cartoonist_id]", options_for_select([["選択してください", ""]] + Cartoonist.all.map { |c| [c.artist_name, c.id] }), { class: "js-searchable", multiple: true } %>
              </div>
              <div class="form-group">
                <%= f.label :campany_name_id, "出版社" %>
                <%= select_tag "comic[publisher_id]", options_for_select([["選択してください", ""]] + Publisher.all.map { |p| [p.company_name, p.id] }), { class: "js-searchable", multiple: true } %>
              </div>
              <div class = "form-group">
                <%= f.submit "Update Comic" %>
              </div>
              <%= link_to "Show", comic_path(@comic.id), class: "btn btn-secondary" %>

              <%= link_to "Back", comics_path, class: "btn btn-secondary" %>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
</main>

app/views/comics/index.html.erb
<main>
  <p id = "notice"><%= flash[:notice] %></p>

  <div class = "container px-5 px-sm-0">
    <div class = "row">
      <div class = "col-md-3">
        <%= render 'layouts/sidebar' %>
      </div>


      <div class = "col-md-8 offset-md-1">
        <h2><i class="fas fa-book-open"></i>Comics</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th>作品名</th>
              <th>レビュー</th>
              <th>作者</th>
              <th>出版社</th>
              <th colspan = "3"></th>
              <Body></Body>
            </tr>
          </thead>
          <tbody>
            <% @comics.each do |comic| %>
            <tr>
              <td><%= link_to comic.title, comic_path(comic.id)  %></td>
              <td><%= comic.body %></td>
              <td><%= comic.cartoonist&.artist_name %></td>
              <td><%= comic.publisher&.company_name %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/comics/new.html.erb
<main>
  <p id="notice"><%= notice %></p>
  <%= form_with model:@comic, url:comics_path, local:true do |f| %>
    <div class = "contailner">
      <div class = "row">
        <div class = "col-sm-12 col-md-8 col-lg-5 p-5 px-sm-0 mx-auto">
          <h2><i class="fas fa-plus"></i>New Comic</h2>
            <% if @comic.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>
                <ul>
                  <% @comic.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>



              <div class = "form-group">
                <%= f.label :title, "作品名" %>
                <%= f.text_field :title %>
              </div>
              <div class = "form-group">
                <%= f.label :body, "レビュー" %>
                <%= f.text_area :body %>
              </div>
              <div class="form-group">
                <%= f.label :artist_name_id, "作者" %>
                <%= select_tag "comic[cartoonist_id]", options_for_select([["選択してください", ""]] + Cartoonist.all.map { |c| [c.artist_name, c.id] }), { class: "js-searchable", multiple: true } %>
              </div>
              <div class="form-group">
                <%= f.label :campany_name_id, "出版社" %>
                <%= select_tag "comic[publisher_id]", options_for_select([["選択してください", ""]] + Publisher.all.map { |p| [p.company_name, p.id] }), { class: "js-searchable", multiple: true } %>
              </div>
              <div class = "form-group">
                <%= f.submit "Create Comic" %>
              </div>
              <div class = "form-group">
                <%= link_to "Back", comics_path, class: "btn btn-secondary" %>
              </div>
              <div class = "form-group">
                <a class = "btn btn-secondary", href = "/terms">
                 このサイトについて
                </a>
              </div>

        </div>
      </div>
    </div>
  <% end %>
</main>

app/views/comics/show.html.erb
<main>
  <p id = "notice"><%= flash[:notice] %></p>

  <div class = "container px-5 px-sm-0" >
    <div class = "row">
      <div class = "col-md-3">
        <%= render 'layouts/sidebar' %>
      </div>


      <div class = "col-md-8 offset-md-1">
        <h2><i class="fas fa-book-open"></i>Comic detail</h2>
        <!--<table class = "table table-hover table-inverse">-->
          <!--<thead>-->
          <!--  <tr>-->
          <!--    <th>作品名</th>-->
          <!--    <th>レビュー</th>-->
          <!--    <th>作者</th>-->
          <!--    <th>出版社</th>-->
          <!--    <th colspan = "3"></th>-->
          <!--  </tr>-->
          <!--</thead>-->
          <!--<tbody>-->
            <!--<tr>-->
              <h3><%= @comic.title %></h3>
              <p><%= @comic.body %></p>
              <p><%= "作者:" %><%= @comic.cartoonist&.artist_name %></br>
              <%= "出版社:" %><%= @comic.publisher&.company_name %></p>
              <% if current_user == @comic.user %>
              <td><%= link_to 'Edit', edit_comic_path(@comic.id), class: "btn btn-secondary" %></td>
              <td><%= link_to 'Destroy', comic_path(@comic), method: :delete, class: "btn btn-secondary" %></td>
              <% end %>
            <!--</tr>-->
          <!--</tbody>-->
        <!--</table>-->
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fas fa-book"></i>
        <strong>Comition</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to
          <i class="fas fa-book"></i>
          <strong>Comition</strong>!!
        </h1>
        <p>In
          <i class="fas fa-book"></i>
          <strong>Comition</strong>,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various comics!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight © 2023 Nakaue All Rights Reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Comition</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
            <%= link_to  user_path(current_user), class:"nav-link text-light" do %>
              <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
            <a class="nav-link text-light" href="/comics/new">
              <i class="fas fa-plus"></i>New Post
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users">
              <i class="fas fa-users"></i>Users
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/comics">
              <i class="fas fa-book-open"></i>Comics
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/publishers">
              <i class="fas fa-building"></i>Publishers
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/cartoonists">
              <i class="fas fa-pen-fancy"></i>Cartoonists
            </a>
          </li>
          <li>
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i>Log out
            </a>
          </li>
          <% else %>
          <li>
            <a class="nav-link text-light" href="/">
              <i class="fas fa-home"></i>Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/home/about">
              <i class="fas fa-link"></i>About
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>Sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
  <h2><i class="fas fa-user"></i>User info</h2>

  <table class="table">
    <tbody>
      <tr><%= attachment_image_tag @user, :profile_image, fallback: "default-image.jpg", size:'100x100' %></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>

      <div class='row'>

          <% if @user == current_user %>
            <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          <% else %>
            <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          <% end %>
          <h5><i class="fas fa-check"></i>How to Use</h5>
          <ul>
             <a class = "btn btn-outline-primary", href = "/terms">
               このサイトについて
             </a>
          </ul>

      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicIntroduction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/terms.html.erb
<main>
  <div class = "contailner">
    <div class = "row">
      <div class = "col-sm-12 col-md-8 col-lg-8 p-5 px-sm-0 mx-auto">
        <h2>このサイトについて</h2>


        <li>漫画のタイトルとレビュー感想などを入力してください。</li>
        <li>出来る限り作者と出版社を選んで欲しいのですが、分からない場合は空欄で構いません。</li>
        <li>現在、作者は付け足している最中ですので、もし足りない人が居た場合とりあえず「その他」を選択してください。</li>
        <li>自身が投稿したものは編集、削除が可能です。</li>
        <li>同様に、自身のユーザーについても編集可能です。</li>
        <!--<li></li>-->


        <h5>運営の目的</h5>
        <li>このWebサイトは面白い漫画を勧めたいという気持ちで運営しています。</li>
        <li>このサイト運営者はプログラミング学習のためにこのサイトを作成しました。</li>
        <li>面白い漫画の感想、絵柄、登場人物の多さなど、どこをおすすめしたいのか教えて下さい。</li>

        <h5>New Postの使い方</h5>
        <li>作者・出版社は複数選択可能な設定にしているので、枠の中で検索していただき、該当の項目を選択してください。</li>
        <li>もし選択肢を検索するボックスが出ていなかったら、一度サイトをリロードしてください。</li>
        <li>レビューは最大250文字しか入力できませんので、書き足りない場合同じ作品に対して複数回投稿していただいてもかまいません。</li>


        <h5>注意事項</h5>
        <li>基本的にネタバレ禁止です。</li>
        <li>マイナス評価をしてもらうことは可能ですが、誹謗中傷はダメです。</li>
        <li>今のところ練習用のサイトなので、予告なく消してしまうこともあります。</li>

      </div>
    </div>
  </div>


</main>

app/views/publishers/index.html.erb
<main>
  <p id = "notice"><%= flash[:notice] %></p>

  <div class = "container px-5 px-sm-0">
    <div class = "row">
      <div class = "col-md-3">
        <%= render 'layouts/sidebar' %>
      </div>


      <div class = "col-md-8 offset-md-1">
        <h2><i class="fas fa-building"></i>Publishers</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th>出版社</th>
              <th colspan = "3"></th>
              <Body></Body>
            </tr>
          </thead>
          <tbody>
            <% @publishers.each do |publisher| %>
            <tr>
              <td><%= link_to publisher.company_name, publisher_path(publisher.id)  %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/publishers/show.html.erb
<main>
  <p id = "notice"><%= flash[:notice] %></p>

  <div class = "container px-5 px-sm-0" >
    <div class = "row">
      <div class = "col-md-3">
        <%= render 'layouts/sidebar' %>
      </div>


      <div class = "col-md-8 offset-md-1">
        <h2><i class="fas fa-building"></i>Publisher detail</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th>作品名</th>
              <th>レビュー</th>
              <th>作者</th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
          <% @publisher.comics.each do |comic| %>
            <tr>
              <td><%= link_to comic.title, comic_path(comic.id) %></td>
              <td><%= comic.body %></td>
              <td><%= comic.cartoonist&.artist_name %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<main>
  <div class = "row">
    <div class = "col-sm-12 col-md-8 col-lg-5 p-5 px-sm-0 mx-auto">
      <h2><i class="fas fa-users"></i>Editing user</h2>
        <% if @user.errors.any? %>
        <div id = "error_explanation">
          <h2><%= @user.errors.count %>error prohibited this user from saved:</h2>
            <ul>
              <% @user.errors.full_message.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
        <% end %>

        <%= form_with model:@user, local:true do |f| %>
          <div class = "form-group">
            <%= f.label :name, "ユーザーネーム" %>
            <%= f.text_field :name %>
          </div>
          <div class = "form-group">
            <%= f.label :profile_image, "プロフィール画像" %>
            <%= f.attachment_field :profile_image %>
          </div>
          <div class = "form-group">
            <%= f.label :introduction, "紹介文" %>
            <%= f.text_area :introduction %>
          </div>
          <div class = "form-group">
            <%= f.submit "Update User" %>
          </div>
        <% end %>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id = "notice"><%= flash[:notice] %></p>

  <div class = "container px-5 px-sm-0">
    <div class = "row">
      <div class = "col-md-3">
        <%= render 'layouts/sidebar' %>
      </div>


      <div class = "col-md-8 offset-md-1">
        <h2><i class="fas fa-users"></i>Users</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>ユーザーネーム</th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag @user, :profile_image, fallback: "default-image.jpg", size:'80x80' %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user.id), class: "btn btn-secondary" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id = "notice"><%= flash[:notice] %></p>

  <div class = "container px-5 px-sm-0" >
    <div class = "row">
      <div class = "col-md-3">
        <%= render 'layouts/sidebar' %>
      </div>


      <div class = "col-md-8 offset-md-1">
        <h2><i class="fas fa-book-open"></i>Comics</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th>作品名</th>
              <th>レビュー</th>
              <th>作者</th>
              <th>出版社</th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @user.comics.each do |comic| %>
            <tr>
              <td><%= link_to comic.title, comic_path(comic.id) %></td>
              <td><%= comic.body %></td>
              <td><%= comic.cartoonist&.artist_name %></td>
              <td><%= comic.publisher&.company_name %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>